// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package todomocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/iamyoki/go-gin-ddd-clean-architecture/module/todo/domain/todo"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// DeleteById provides a mock function for the type MockRepository
func (_mock *MockRepository) DeleteById(ctx context.Context, id uuid.UUID) (*todo.Todo, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteById")
	}

	var r0 *todo.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*todo.Todo, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *todo.Todo); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*todo.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_DeleteById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteById'
type MockRepository_DeleteById_Call struct {
	*mock.Call
}

// DeleteById is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepository_Expecter) DeleteById(ctx interface{}, id interface{}) *MockRepository_DeleteById_Call {
	return &MockRepository_DeleteById_Call{Call: _e.mock.On("DeleteById", ctx, id)}
}

func (_c *MockRepository_DeleteById_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepository_DeleteById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_DeleteById_Call) Return(todo1 *todo.Todo, err error) *MockRepository_DeleteById_Call {
	_c.Call.Return(todo1, err)
	return _c
}

func (_c *MockRepository_DeleteById_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*todo.Todo, error)) *MockRepository_DeleteById_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockRepository
func (_mock *MockRepository) FindAll(ctx context.Context) ([]todo.Todo, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []todo.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]todo.Todo, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []todo.Todo); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]todo.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) FindAll(ctx interface{}) *MockRepository_FindAll_Call {
	return &MockRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *MockRepository_FindAll_Call) Run(run func(ctx context.Context)) *MockRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_FindAll_Call) Return(todos []todo.Todo, err error) *MockRepository_FindAll_Call {
	_c.Call.Return(todos, err)
	return _c
}

func (_c *MockRepository_FindAll_Call) RunAndReturn(run func(ctx context.Context) ([]todo.Todo, error)) *MockRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindById provides a mock function for the type MockRepository
func (_mock *MockRepository) FindById(ctx context.Context, id uuid.UUID) (*todo.Todo, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 *todo.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*todo.Todo, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *todo.Todo); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*todo.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type MockRepository_FindById_Call struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepository_Expecter) FindById(ctx interface{}, id interface{}) *MockRepository_FindById_Call {
	return &MockRepository_FindById_Call{Call: _e.mock.On("FindById", ctx, id)}
}

func (_c *MockRepository_FindById_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepository_FindById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindById_Call) Return(todo1 *todo.Todo, err error) *MockRepository_FindById_Call {
	_c.Call.Return(todo1, err)
	return _c
}

func (_c *MockRepository_FindById_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*todo.Todo, error)) *MockRepository_FindById_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockRepository
func (_mock *MockRepository) Save(ctx context.Context, todo1 *todo.Todo) error {
	ret := _mock.Called(ctx, todo1)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *todo.Todo) error); ok {
		r0 = returnFunc(ctx, todo1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - todo1 *todo.Todo
func (_e *MockRepository_Expecter) Save(ctx interface{}, todo1 interface{}) *MockRepository_Save_Call {
	return &MockRepository_Save_Call{Call: _e.mock.On("Save", ctx, todo1)}
}

func (_c *MockRepository_Save_Call) Run(run func(ctx context.Context, todo1 *todo.Todo)) *MockRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *todo.Todo
		if args[1] != nil {
			arg1 = args[1].(*todo.Todo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Save_Call) Return(err error) *MockRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Save_Call) RunAndReturn(run func(ctx context.Context, todo1 *todo.Todo) error) *MockRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
