// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecasemocks

import (
	"github.com/iamyoki/go-gin-ddd-clean-architecture/app/appcontext"
	"github.com/iamyoki/go-gin-ddd-clean-architecture/module/iam/usecase"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHasher creates a new instance of MockHasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHasher {
	mock := &MockHasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHasher is an autogenerated mock type for the Hasher type
type MockHasher struct {
	mock.Mock
}

type MockHasher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHasher) EXPECT() *MockHasher_Expecter {
	return &MockHasher_Expecter{mock: &_m.Mock}
}

// HashPassowrd provides a mock function for the type MockHasher
func (_mock *MockHasher) HashPassowrd(password string) (string, error) {
	ret := _mock.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for HashPassowrd")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(password)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHasher_HashPassowrd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashPassowrd'
type MockHasher_HashPassowrd_Call struct {
	*mock.Call
}

// HashPassowrd is a helper method to define mock.On call
//   - password string
func (_e *MockHasher_Expecter) HashPassowrd(password interface{}) *MockHasher_HashPassowrd_Call {
	return &MockHasher_HashPassowrd_Call{Call: _e.mock.On("HashPassowrd", password)}
}

func (_c *MockHasher_HashPassowrd_Call) Run(run func(password string)) *MockHasher_HashPassowrd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHasher_HashPassowrd_Call) Return(s string, err error) *MockHasher_HashPassowrd_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockHasher_HashPassowrd_Call) RunAndReturn(run func(password string) (string, error)) *MockHasher_HashPassowrd_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyPassword provides a mock function for the type MockHasher
func (_mock *MockHasher) VerifyPassword(hashedPassword string, password string) bool {
	ret := _mock.Called(hashedPassword, password)

	if len(ret) == 0 {
		panic("no return value specified for VerifyPassword")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = returnFunc(hashedPassword, password)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockHasher_VerifyPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyPassword'
type MockHasher_VerifyPassword_Call struct {
	*mock.Call
}

// VerifyPassword is a helper method to define mock.On call
//   - hashedPassword string
//   - password string
func (_e *MockHasher_Expecter) VerifyPassword(hashedPassword interface{}, password interface{}) *MockHasher_VerifyPassword_Call {
	return &MockHasher_VerifyPassword_Call{Call: _e.mock.On("VerifyPassword", hashedPassword, password)}
}

func (_c *MockHasher_VerifyPassword_Call) Run(run func(hashedPassword string, password string)) *MockHasher_VerifyPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHasher_VerifyPassword_Call) Return(b bool) *MockHasher_VerifyPassword_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockHasher_VerifyPassword_Call) RunAndReturn(run func(hashedPassword string, password string) bool) *MockHasher_VerifyPassword_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthToken creates a new instance of MockAuthToken. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthToken(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthToken {
	mock := &MockAuthToken{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthToken is an autogenerated mock type for the AuthToken type
type MockAuthToken struct {
	mock.Mock
}

type MockAuthToken_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthToken) EXPECT() *MockAuthToken_Expecter {
	return &MockAuthToken_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function for the type MockAuthToken
func (_mock *MockAuthToken) Generate(activeUser appcontext.ActiveUser) (usecase.TokenPair, error) {
	ret := _mock.Called(activeUser)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 usecase.TokenPair
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(appcontext.ActiveUser) (usecase.TokenPair, error)); ok {
		return returnFunc(activeUser)
	}
	if returnFunc, ok := ret.Get(0).(func(appcontext.ActiveUser) usecase.TokenPair); ok {
		r0 = returnFunc(activeUser)
	} else {
		r0 = ret.Get(0).(usecase.TokenPair)
	}
	if returnFunc, ok := ret.Get(1).(func(appcontext.ActiveUser) error); ok {
		r1 = returnFunc(activeUser)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthToken_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockAuthToken_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - activeUser appcontext.ActiveUser
func (_e *MockAuthToken_Expecter) Generate(activeUser interface{}) *MockAuthToken_Generate_Call {
	return &MockAuthToken_Generate_Call{Call: _e.mock.On("Generate", activeUser)}
}

func (_c *MockAuthToken_Generate_Call) Run(run func(activeUser appcontext.ActiveUser)) *MockAuthToken_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 appcontext.ActiveUser
		if args[0] != nil {
			arg0 = args[0].(appcontext.ActiveUser)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthToken_Generate_Call) Return(tokenPair usecase.TokenPair, err error) *MockAuthToken_Generate_Call {
	_c.Call.Return(tokenPair, err)
	return _c
}

func (_c *MockAuthToken_Generate_Call) RunAndReturn(run func(activeUser appcontext.ActiveUser) (usecase.TokenPair, error)) *MockAuthToken_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function for the type MockAuthToken
func (_mock *MockAuthToken) Refresh(refreshToken string) (usecase.TokenPair, error) {
	ret := _mock.Called(refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 usecase.TokenPair
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (usecase.TokenPair, error)); ok {
		return returnFunc(refreshToken)
	}
	if returnFunc, ok := ret.Get(0).(func(string) usecase.TokenPair); ok {
		r0 = returnFunc(refreshToken)
	} else {
		r0 = ret.Get(0).(usecase.TokenPair)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(refreshToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthToken_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type MockAuthToken_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - refreshToken string
func (_e *MockAuthToken_Expecter) Refresh(refreshToken interface{}) *MockAuthToken_Refresh_Call {
	return &MockAuthToken_Refresh_Call{Call: _e.mock.On("Refresh", refreshToken)}
}

func (_c *MockAuthToken_Refresh_Call) Run(run func(refreshToken string)) *MockAuthToken_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthToken_Refresh_Call) Return(tokenPair usecase.TokenPair, err error) *MockAuthToken_Refresh_Call {
	_c.Call.Return(tokenPair, err)
	return _c
}

func (_c *MockAuthToken_Refresh_Call) RunAndReturn(run func(refreshToken string) (usecase.TokenPair, error)) *MockAuthToken_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function for the type MockAuthToken
func (_mock *MockAuthToken) Verify(accessToken string) (*appcontext.ActiveUser, error) {
	ret := _mock.Called(accessToken)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 *appcontext.ActiveUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*appcontext.ActiveUser, error)); ok {
		return returnFunc(accessToken)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *appcontext.ActiveUser); ok {
		r0 = returnFunc(accessToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*appcontext.ActiveUser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(accessToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthToken_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockAuthToken_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - accessToken string
func (_e *MockAuthToken_Expecter) Verify(accessToken interface{}) *MockAuthToken_Verify_Call {
	return &MockAuthToken_Verify_Call{Call: _e.mock.On("Verify", accessToken)}
}

func (_c *MockAuthToken_Verify_Call) Run(run func(accessToken string)) *MockAuthToken_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthToken_Verify_Call) Return(activeUser *appcontext.ActiveUser, err error) *MockAuthToken_Verify_Call {
	_c.Call.Return(activeUser, err)
	return _c
}

func (_c *MockAuthToken_Verify_Call) RunAndReturn(run func(accessToken string) (*appcontext.ActiveUser, error)) *MockAuthToken_Verify_Call {
	_c.Call.Return(run)
	return _c
}
